theme: jekyll-theme-slate
title: ibuibu268
description: ibuibu268 website (Github Pages)

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: 'google2dc8aead0c768bf1.html'
    values:
      sitemap: false
